import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/question.dart';

class QuizPdfService {
  static Future<void> generateQuizReport({
    required List<Question> questions,
    required Map<int, String> userAnswers,
    required Map<int, List<String>> displayedOptions,
    required Set<int> timedOutQuestions,
    required int score,
    required int points,
    required String category,
    required int setNumber,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();

    final fileName = _generateFileName(category, now);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),

        header: (context) {
          return pw.Container(
            padding: const pw.EdgeInsets.only(bottom: 8),
            margin: const pw.EdgeInsets.only(bottom: 15),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(width: 0.5, color: PdfColors.grey),
              ),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'DevOps Quiz',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.Text('Quiz Report', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          );
        },

        footer: (context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(top: 10),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by DevOps Quiz',
                  style: const pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.Text(
                  'Page ${context.pageNumber} '
                  'of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 9,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          );
        },

        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                'Quiz Report',
                style: pw.TextStyle(
                  fontSize: 25,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),

            pw.SizedBox(height: 8),

            pw.Center(
              child: pw.Text(
                _quizName(category, setNumber),
                style: const pw.TextStyle(
                  fontSize: 15,
                  color: PdfColors.grey700,
                ),
              ),
            ),

            pw.SizedBox(height: 20),

            _buildSummary(
              questions: questions,
              userAnswers: userAnswers,
              score: score,
              points: points,
              now: now,
            ),

            pw.SizedBox(height: 25),

            pw.Text(
              'Questions and Answers',
              style: pw.TextStyle(fontSize: 19, fontWeight: pw.FontWeight.bold),
            ),

            pw.SizedBox(height: 12),

            ...List.generate(questions.length, (index) {
              return _buildQuestion(
                number: index + 1,
                question: questions[index],
                options: displayedOptions[index] ?? <String>[],
                userAnswer: userAnswers[index],
                timedOut: timedOutQuestions.contains(index),
              );
            }),
          ];
        },
      ),
    );

    final Uint8List bytes = await pdf.save();

    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }

  static pw.Widget _buildSummary({
    required List<Question> questions,
    required Map<int, String> userAnswers,
    required int score,
    required int points,
    required DateTime now,
  }) {
    final answered = userAnswers.length;

    final wrong = answered - score;

    final unanswered = questions.length - answered;

    final percentage = questions.isEmpty ? 0.0 : score / questions.length * 100;

    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColors.grey400),
      ),
      child: pw.Column(
        children: [
          _summaryRow('Score', '$score / ${questions.length}'),
          _summaryRow('Percentage', '${percentage.toStringAsFixed(0)}%'),
          _summaryRow('Correct', '$score'),
          _summaryRow('Wrong', '$wrong'),
          _summaryRow('Not Answered', '$unanswered'),
          _summaryRow('Points', '$points'),
          _summaryRow(
            'Date',
            '${_two(now.day)}/'
                '${_two(now.month)}/'
                '${now.year}',
          ),
          _summaryRow(
            'Time',
            '${_two(now.hour)}:'
                '${_two(now.minute)}:'
                '${_two(now.second)}',
          ),
        ],
      ),
    );
  }

  static pw.Widget _summaryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.Text(value),
        ],
      ),
    );
  }

  static pw.Widget _buildQuestion({
    required int number,
    required Question question,
    required List<String> options,
    required String? userAnswer,
    required bool timedOut,
  }) {
    final bool correct = userAnswer != null && userAnswer == question.answer;

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Question $number',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),

          if (question.category.trim().isNotEmpty) ...[
            pw.SizedBox(height: 3),
            pw.Text(
              'Category: ${question.category}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ],

          pw.SizedBox(height: 8),

          pw.Text(
            question.question,
            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 10),

          pw.Text(
            'Options:',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 5),

          ...List.generate(options.length, (index) {
            final letter = String.fromCharCode(65 + index);

            return pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 3),
              child: pw.Text(
                '$letter. ${options[index]}',
                style: const pw.TextStyle(fontSize: 11),
              ),
            );
          }),

          pw.SizedBox(height: 8),

          pw.Divider(),

          pw.Text(
            'Your Answer: '
            '${userAnswer ?? (timedOut ? "Not Answered - Time Out" : "Not Answered")}',
          ),

          pw.SizedBox(height: 4),

          pw.Text(
            'Correct Answer: '
            '${question.answer}',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 4),

          pw.Text(
            userAnswer == null
                ? 'Result: Not Answered'
                : correct
                ? 'Result: Correct'
                : 'Result: Incorrect',
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: userAnswer == null
                  ? PdfColors.orange
                  : correct
                  ? PdfColors.green
                  : PdfColors.red,
            ),
          ),
        ],
      ),
    );
  }

  static String _quizName(String category, int setNumber) {
    if (category == 'DailyQuiz') {
      return 'Daily Quiz';
    }

    if (category == 'DevOps') {
      return 'DevOps Quiz';
    }

    return '$category - Set $setNumber';
  }

  static String _generateFileName(String category, DateTime now) {
    String safeCategory;

    if (category == 'DailyQuiz') {
      safeCategory = 'Daily_Quiz';
    } else {
      safeCategory = category.replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_');
    }

    final timestamp =
        '${now.year}-'
        '${_two(now.month)}-'
        '${_two(now.day)}_'
        '${_two(now.hour)}-'
        '${_two(now.minute)}-'
        '${_two(now.second)}';

    return '${safeCategory}_Quiz_Report_'
        '$timestamp.pdf';
  }

  static String _two(int number) {
    return number.toString().padLeft(2, '0');
  }
}
