// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNPUzHseL5XWlRjub1DuqCWHGlpXMUDUA',
    appId: '1:742868981766:web:5cccb68450eca23d64cb87',
    messagingSenderId: '742868981766',
    projectId: 'devops-quiz-13395',
    authDomain: 'devops-quiz-13395.firebaseapp.com',
    storageBucket: 'devops-quiz-13395.firebasestorage.app',
    measurementId: 'G-G96KMDG1LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffP67uhZH4r1V_23dxycVTeI12xy8OsI',
    appId: '1:742868981766:android:914c060b802a0e0f64cb87',
    messagingSenderId: '742868981766',
    projectId: 'devops-quiz-13395',
    storageBucket: 'devops-quiz-13395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OF8H7aMRmy99rVUrokMqr5BGYpdOAWQ',
    appId: '1:742868981766:ios:eae7987f5b59996864cb87',
    messagingSenderId: '742868981766',
    projectId: 'devops-quiz-13395',
    storageBucket: 'devops-quiz-13395.firebasestorage.app',
    iosBundleId: 'com.nayan.devops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9OF8H7aMRmy99rVUrokMqr5BGYpdOAWQ',
    appId: '1:742868981766:ios:eae7987f5b59996864cb87',
    messagingSenderId: '742868981766',
    projectId: 'devops-quiz-13395',
    storageBucket: 'devops-quiz-13395.firebasestorage.app',
    iosBundleId: 'com.nayan.devops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNPUzHseL5XWlRjub1DuqCWHGlpXMUDUA',
    appId: '1:742868981766:web:064c210164dc3a3164cb87',
    messagingSenderId: '742868981766',
    projectId: 'devops-quiz-13395',
    authDomain: 'devops-quiz-13395.firebaseapp.com',
    storageBucket: 'devops-quiz-13395.firebasestorage.app',
    measurementId: 'G-PW1G6CTW9V',
  );
}
